"""
Django settings for project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import datetime
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Generated for public repo with ./manage.py generate_secret_key take care to change it
SECRET_KEY = "$x8^22cb@s$!sat+8d&nnpqp%6de^c+9%@!swj2hu_t28l5^*o"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"

ENVIRONMENT = "production"

if ENVIRONMENT in ("PRODUCTION", "PREPRODUCTION"):
    SCHEME = "https://"
else:
    SCHEME = "http://"

HOSTNAME = "foo.gouv.fr"
# Without trailing slash
CLIENT_ENDPOINT = ""
SERVER_ENDPOINT = "/api"
CLIENT_PORT = ""
SERVER_PORT = ""

HTTP_CLIENT_ORIGIN_URL = SCHEME + HOSTNAME + CLIENT_PORT
HTTP_SERVER_ORIGIN_URL = SCHEME + HOSTNAME + SERVER_PORT
HTTP_CLIENT_URL = HTTP_CLIENT_ORIGIN_URL + CLIENT_ENDPOINT
HTTP_SERVER_URL = HTTP_SERVER_ORIGIN_URL + SERVER_ENDPOINT

# https://partenaires.franceconnect.gouv.fr/
FRANCE_CONNECT_URL_ROOT = "https://app.franceconnect.gouv.fr/api/v1/"
FRANCE_CONNECT_CLIENT_ID = ""
FRANCE_CONNECT_CLIENT_SECRET = ""

FRANCE_CONNECT_URLS = {
    "authorize": FRANCE_CONNECT_URL_ROOT + "authorize",
    "token": FRANCE_CONNECT_URL_ROOT + "token",
    "userinfo": FRANCE_CONNECT_URL_ROOT + "userinfo",
    "logout": FRANCE_CONNECT_URL_ROOT + "logout",
}
FRANCE_CONNECT_URL_CALLBACK = HTTP_CLIENT_URL + "/fc/callback"
FRANCE_CONNECT_URL_POST_LOGOUT = HTTP_CLIENT_URL + "/fc/postlogout"

JWT_EXPIRATION_DELTA = datetime.timedelta(seconds=3600 * 24)
JWT_PAYLOAD_HANDLER = "project.franceconnect.jwt.jwt_payload_handler"
